name: Continuous Integration

on: [push, pull_request]
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  Linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Linting
        run: |
          pip install pre-commit
          pre-commit run --all-files
  Tests:
    needs: Linting
    name: Tests ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[dev]

      - name: Run pytest
        shell: bash
        run: pytest --cov=turbomoleio --cov-report=xml -m "not integration"
#        run: pytest -m 'not integration'
